#!/bin/bash

echo "🚀 SafeTap Admin Dashboard - Deployment Helper"
echo "============================================="
echo ""

echo "📋 Pre-deployment checklist:"
echo ""
echo "1. ✅ Proyecto compilado exitosamente"
echo "2. ⚠️  Configurar variables de entorno en Vercel:"
echo "   - DATABASE_URL (misma que la app principal)"
echo "   - NEXTAUTH_URL (https://admin.tusitio.com)"
echo "   - NEXTAUTH_SECRET (secreto de producción)"
echo "   - GOOGLE_CLIENT_ID"
echo "   - GOOGLE_CLIENT_SECRET"
echo ""
echo "3. ⚠️  Configurar dominio personalizado en Vercel:"
echo "   - Project Settings > Domains"
echo "   - Agregar: admin.tusitio.com"
echo "   - Configurar DNS CNAME: admin.tusitio.com -> cname.vercel-dns.com"
echo ""
echo "4. ⚠️  Configurar Build Settings:"
echo "   - Root Directory: admin-dashboard"
echo "   - Build Command: npm run build"
echo "   - Output Directory: .next"
echo ""
echo "🔧 Para ejecutar en desarrollo:"
echo "npm run dev"
echo ""
echo "🏗️  Para build de producción:"
echo "npm run build"
echo ""
echo "🌐 Para iniciar servidor de producción:"
echo "npm start"
echo ""
echo "📚 Ver README.md para instrucciones detalladas de deployment"
